export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f4f7fb",
    fontFamily: "Arial, sans-serif",
    color: "#1e293b",
    padding: 20,
  },
  container: {
    maxWidth: 1280,
    margin: "0 auto",
  },
  hero: {
    background: "linear-gradient(135deg, #ffffff, #eef4ff)",
    borderRadius: 28,
    padding: "clamp(16px, 4vw, 24px)",
    boxShadow: "0 8px 24px rgba(15,23,42,0.08)",
    display: "grid",
    gap: 20,
  },
  badge: {
    display: "inline-block",
    background: "#dbeafe",
    color: "#1d4ed8",
    padding: "6px 12px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 12,
    marginBottom: 12,
  },
 title: {
  margin: 0,
  fontSize: "clamp(24px, 5vw, 38px)",
  lineHeight: 1.3,
  wordBreak: "break-word",
},
 subtitle: {
  marginTop: 10,
  lineHeight: 1.7,
  color: "#475569",
  maxWidth: 900,
  fontSize: "clamp(14px, 3vw, 18px)",
},
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  statCard: {
    background: "#fff",
    borderRadius: 18,
    padding: 16,
    textAlign: "center",
    boxShadow: "0 4px 16px rgba(15,23,42,0.05)",
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 800,
  },
  statLabel: {
    marginTop: 6,
    fontSize: 14,
    color: "#64748b",
  },
  tabRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    margin: "20px 0",
  },
    tabButton: {
    border: "none",
    background: "#fff",
    color: "#1e293b",
    borderRadius: 14,
    padding: "12px 16px",
    cursor: "pointer",
    fontWeight: 700,
    boxShadow: "0 4px 12px rgba(15,23,42,0.05)",
  },

 audioBtn: {
  border: "none",
  background: "#fff",
  color: "#1e293b",
  borderRadius: 14,
  padding: "12px 16px",
  cursor: "pointer",
  fontWeight: 700,
  boxShadow: "0 4px 12px rgba(15,23,42,0.05)",
  minWidth: 48,
  minHeight: 48,
  touchAction: "manipulation",
  WebkitTapHighlightColor: "transparent",
},
  tabButtonActive: {
    background: "#2563eb",
    color: "#fff",
  },
twoCol: {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))",
  gap: 20,
},
  sidePanel: {
    background: "#fff",
    borderRadius: 22,
    padding: 18,
    boxShadow: "0 8px 24px rgba(15,23,42,0.06)",
    alignSelf: "start",
  },
  mainPanel: {
    background: "#fff",
    borderRadius: 22,
    padding: 20,
    boxShadow: "0 8px 24px rgba(15,23,42,0.06)",
  },
  panelTitle: {
    marginTop: 0,
    marginBottom: 10,
  },
  sideBtn: {
    width: "100%",
    display: "flex",
    gap: 10,
    alignItems: "center",
    textAlign: "left",
    border: "none",
    padding: 12,
    borderRadius: 14,
    marginBottom: 8,
    cursor: "pointer",
    background: "#eff6ff",
color: "#1e293b",
    fontWeight: 700,
  },
  sideBtnActive: {
    background: "#2563eb",
 color: "#ffffff",
  },
  noteBox: {
    marginTop: 16,
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    borderRadius: 16,
    padding: 14,
    lineHeight: 1.7,
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  muted: {
    color: "#64748b",
    lineHeight: 1.7,
  },
  searchInput: {
    minWidth: 280,
    padding: 12,
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    fontSize: 14,
  },
  gridCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  wordCard: {
    background: "#f8fafc",
color: "#1e293b",
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    padding: 16,
    lineHeight: 1.8,
  },
  zh: {
    fontSize: 18,
  },
  sectionBlock: {
    marginTop: 20,
  },
  tableWrap: {
    overflowX: "auto",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: 12,
    background: "#eff6ff",
    borderBottom: "1px solid #dbeafe",
  },
  td: {
    padding: 12,
    borderBottom: "1px solid #e2e8f0",
  },
  pillWrap: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 12,
  },
  pill: {
    background: "#eef2ff",
    color: "#1e3a8a",
    padding: "10px 14px",
    borderRadius: 999,
    fontWeight: 700,
  },
  grammarWrap: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 16,
  },
  grammarSection: {
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    padding: 16,
    background: "#f8fafc",
  },
  grammarItem: {
    background: "#fff",
    borderRadius: 14,
    padding: 12,
    marginTop: 10,
    border: "1px solid #e2e8f0",
  },
  formula: {
    margin: "8px 0",
    display: "inline-block",
    background: "#dbeafe",
    color: "#1d4ed8",
    padding: "6px 10px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 13,
  },
  roadmapGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
    marginTop: 16,
  },
  roadCard: {
    background: "#f8fafc",
    borderRadius: 18,
    padding: 16,
    border: "1px solid #e2e8f0",
    lineHeight: 1.7,
  },
};