export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f7f9fa",
    fontFamily: "var(--sans)",
    color: "#3c3c3c",
    padding: "clamp(12px, 3vw, 24px)",
    boxSizing: "border-box",
  },
  container: {
    maxWidth: 1200,
    margin: "0 auto",
  },
  hero: {
    background: "#ffffff",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 24,
    padding: "clamp(20px, 4vw, 32px)",
    display: "grid",
    gap: 20,
    marginBottom: 28,
  },
  badge: {
    display: "inline-block",
    background: "#ddf4ff",
    color: "#1899d6",
    border: "2px solid #84d8ff",
    padding: "6px 14px",
    borderRadius: 999,
    fontWeight: 800,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "1px",
    marginBottom: 12,
  },
  title: {
    margin: 0,
    fontSize: "clamp(24px, 5vw, 36px)",
    fontWeight: 850,
    lineHeight: 1.2,
    color: "#1a1a1a",
  },
  subtitle: {
    marginTop: 8,
    lineHeight: 1.6,
    color: "#777777",
    maxWidth: 900,
    fontSize: "clamp(14px, 3vw, 16px)",
    fontWeight: 600,
  },
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 16,
    marginTop: 8,
  },
  statCard: {
    background: "#ffffff",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 18,
    padding: 16,
    textAlign: "center",
    cursor: "default",
  },
  statNumber: {
    fontSize: 26,
    fontWeight: 800,
    color: "#58cc02", // Duolingo green
  },
  statLabel: {
    marginTop: 4,
    fontSize: 12,
    color: "#777777",
    fontWeight: 750,
  },
  tabRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    margin: "24px 0",
    padding: 6,
    background: "#ffffff",
    borderRadius: 16,
    border: "2px solid #e5e5e5",
  },
  tabButton: {
    border: "2px solid transparent",
    background: "transparent",
    color: "#777777",
    borderRadius: 12,
    padding: "10px 16px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: 14,
    transition: "all 0.15s ease-in-out",
  },
  tabButtonActive: {
    background: "#ddf4ff",
    color: "#1899d6",
    border: "2px solid #84d8ff",
  },
  audioBtn: {
    border: "2px solid #e5e5e5",
    borderBottom: "4px solid #e5e5e5",
    background: "#ffffff",
    color: "#1cb0f6",
    borderRadius: "50%",
    width: 44,
    height: 44,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.1s, border-color 0.2s",
    outline: "none",
    fontSize: 16,
  },
  twoCol: {
    display: "grid",
    gridTemplateColumns: "280px 1fr",
    gap: 24,
  },
  sidePanel: {
    background: "#ffffff",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 22,
    padding: 16,
    alignSelf: "start",
  },
  mainPanel: {
    background: "#ffffff",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 22,
    padding: "clamp(16px, 4vw, 24px)",
  },
  panelTitle: {
    marginTop: 0,
    marginBottom: 16,
    fontSize: 17,
    fontWeight: 800,
    color: "#1a1a1a",
  },
  sideBtn: {
    width: "100%",
    display: "flex",
    gap: 10,
    alignItems: "center",
    textAlign: "left",
    border: "2px solid #e5e5e5",
    borderBottom: "4px solid #e5e5e5",
    padding: "12px 14px",
    borderRadius: 14,
    marginBottom: 8,
    cursor: "pointer",
    background: "#ffffff",
    color: "#3c3c3c",
    fontWeight: 700,
    fontSize: 14,
    transition: "transform 0.1s, background-color 0.15s",
  },
  sideBtnActive: {
    background: "#ddf4ff",
    color: "#1899d6",
    border: "2px solid #84d8ff",
    borderBottom: "4px solid #84d8ff",
  },
  noteBox: {
    marginTop: 16,
    background: "#fffbeb",
    border: "2px solid #fef3c7",
    borderRadius: 16,
    padding: 16,
    lineHeight: 1.6,
    fontSize: 14,
    color: "#b45309",
    fontWeight: 600,
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 24,
  },
  muted: {
    color: "#777777",
    fontSize: 14,
    lineHeight: 1.6,
    marginTop: 4,
    fontWeight: 600,
  },
  searchInput: {
    minWidth: 260,
    padding: "12px 16px",
    borderRadius: 14,
    border: "2px solid #e5e5e5",
    background: "#ffffff",
    color: "#3c3c3c",
    fontSize: 14,
    outline: "none",
    fontWeight: 600,
    transition: "border-color 0.2s",
  },
  gridCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 16,
  },
  wordCard: {
    background: "#ffffff",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 20,
    padding: 18,
    lineHeight: 1.6,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    transition: "border-color 0.2s",
    color: "#3c3c3c",
  },
  sectionBlock: {
    marginTop: 24,
  },
  tableWrap: {
    overflowX: "auto",
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    borderRadius: 18,
    background: "#ffffff",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: 14,
    background: "#f7f9fa",
    color: "#1a1a1a",
    fontWeight: 800,
    borderBottom: "2px solid #e5e5e5",
  },
  td: {
    padding: 14,
    borderBottom: "2px solid #e5e5e5",
    color: "#3c3c3c",
    fontWeight: 600,
  },
  pillWrap: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 12,
  },
  pill: {
    background: "#f1f1f1",
    color: "#4b5563",
    padding: "6px 12px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 12,
    border: "2px solid #e5e5e5",
  },
  grammarWrap: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 16,
  },
  grammarSection: {
    border: "2px solid #e5e5e5",
    borderRadius: 20,
    padding: 16,
    background: "#ffffff",
  },
  grammarItem: {
    background: "#f7f9fa",
    borderRadius: 16,
    padding: 14,
    marginTop: 12,
    border: "2px solid #e5e5e5",
  },
  formula: {
    margin: "8px 0",
    display: "inline-block",
    background: "#ddf4ff",
    color: "#1899d6",
    padding: "6px 12px",
    borderRadius: 999,
    fontWeight: 800,
    fontSize: 12,
    border: "2px solid #84d8ff",
  },
  roadmapGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 16,
    marginTop: 16,
  },
  roadCard: {
    background: "#ffffff",
    borderRadius: 20,
    padding: 18,
    border: "2px solid #e5e5e5",
    borderBottom: "5px solid #e5e5e5",
    lineHeight: 1.6,
  },
};